### PR TITLE
Laravel 5 support

### PR DESCRIPTION
**Pull request by stayallive**
Title says it all, this however would require this PR to be merged (https://github.com/machuga/authority/pull/27) and the version to be changed in the composer.json for this PR.

### CODE REVIEW

**Comment by machuga** [comment]
So I wholly love the idea of this and the removal if the config-file-esque service provider usage, but I'm not sure putting into master is great yet.  I might need to branch off for L4 support

**Comment by Stayallive** [comment]
Whichever way you wish to go :+1:

**Comment by RomainLanz** [comment]
What do you think of renaming your package to laravel-authority? And set 2 branches, one named 4.0 and one named 5.0.

Would be better for updating your package after that IMO.
You can still have this one on packagist and create a new repository.

**Comment by machuga** [comment]
Branching is likely fine.  I think github will forward requests to a renamed repo for X amount of time but I can't remember.  I'd be fine with authority-laravel as the name.

**Comment by stokic** [comment]
New package name and additional L4 branch would be great!

**Comment by tortuetorche** [comment]
@machuga Do you plan to merge this pull request soon?
If you don't have much time, it'll be easier to merge it in a `l5` branch.
Then we can do this: `composer require machuga/authority-l4:dev-l5` to install it.

**Comment by machuga** [comment]
Ya doing it to a branch will be best because I don't want to break L4 anyway

**Comment by Stayallive** [comment]
@machuga how would you like to handle this one? Maybe open a new repo for L5 (following the "naming convention" of this package? Or just branch and alias on packagist?

I think leaving any authority-l4 traces (that the user will need to type) will be confusing, although you could also integrate the serviceprovider in the main Authority package.

**Comment by machuga** [comment]
I try to keep all the of the Laravel specific stuff out of the main repo since it's framework agnostic.  In the 3.0 release, if I ever release it, the event system is removed as well.

I feel like renaming this repo to authority-laravel with an l4 and l5 branch may be a good way to do it.  Thoughts?

**Comment by stokic** [comment]
IMO that's a good idea, rename and 2 branches

**Comment by Stayallive** [comment]
Big fan :+1: (also of a possible 3.0 of Authority)

**Comment by tortuetorche** [comment]
IMO, the repository renaming is not the priority but a `l5` branch, based on the @Stayallive work, will be really helpful.

**Comment by machuga** [comment]
@Stayallive do you have any interest in managing an authority-laravel repo?  This one has always been managed by someone else (Conar Welsh) and I don't have time to properly invest in it.

**Comment by RomainLanz** [comment]
I'm going to create an ACL system like yours but I'll allow user to store permission on the database and use the system of Middleware to set directly on the route file permission.

**Comment by machuga** [comment]
@RomainLanz You might want to check out Lock - I think it lets you do that out of the box

**Comment by RomainLanz** [comment]
I already have check https://github.com/kodeine/laravel-acl but it's seems to young for the moment.

I'll look at Lock, thanks!

**Comment by Stayallive** [comment]
@machuga, I would certainly not object :)

**Pull request closed without merging**
